document.addEventListener('DOMContentLoaded', () => {
    const services = [
        ['Kat Karşılığı', 'kat-karsiligi.html'], ['Yap-Sat', 'yap-sat.html'], ['Kentsel Dönüşüm', 'kentsel-donusum.html'], ['Arsa Geliştirme', 'arsa-gelistirme.html'], ['Anahtar Teslim', 'anahtar-teslim.html'], ['Mimari Proje', 'mimari-proje.html'], ['Ruhsat Takibi', 'ruhsat-takibi.html'], ['Tadilat', 'tadilat.html'], ['İç Mimari', 'ic-mimari.html'], ['Ofis & Dükkan', 'ofis-dukkan.html'], ['Villa İnşaatı', 'villa-insaati.html'], ['Cephe Yenileme', 'cephe-yenileme.html'], ['İzolasyon İşleri', 'izolasyon-isleri.html'], ['Depo & Sanayi Yapıları', 'depo-sanayi-yapilari.html'], ['Arsa Fizibilitesi', 'arsa-fizibilitesi.html'], ['Gayrimenkul Danışmanlığı', 'gayrimenkul-danismanligi.html'], ['Proje Yönetimi', 'proje-yonetimi.html'], ['Şantiye Yönetimi', 'santiye-yonetimi.html']
    ];
    const content = {
        'ruhsat-takibi': ['Ruhsat Takibi', 'Ruhsat Takibi, projenin idari ve teknik koordinasyonunu doğru sıraya koymaktır. Tekirdağ ve Süleymanpaşa’da mimari proje, ilgili disiplinler, resmi başvuru dosyaları ve uygulama gereklilikleri dikkatle takip edilmelidir. Pioneer, kararların sahaya aktarılabilir olmasını gözetir.', 'Ruhsat sürecini tasarımdan ayrı bir evrak işi olarak değil, uygulamanın sağlam başlangıcı olarak ele alırız. Gerekli koordinasyonları görünür bir programla yöneterek proje, izin ve şantiye aşamaları arasında süreklilik kurarız.', 'Ruhsat sürecinde doğru dosya ve doğru takip, yapım sürecindeki belirsizlikleri azaltır. Projenizin mevcut durumunu ve ihtiyaç duyduğu ana adımları birlikte değerlendirebiliriz.', ['Dosya hazırlığı', 'Mimari proje ve gerekli teknik girdileri başvuru planına göre düzenleriz.'], ['Kurum koordinasyonu', 'Süreçteki kontrol ve talep akışını planlı biçimde izleriz.'], ['Uygulamaya geçiş', 'Ruhsat kararını şantiye programı ve proje yönetimiyle ilişkilendiririz.']],
        'tadilat': ['Tadilat', 'Tadilat, mevcut mekânı yalnızca yenilemek değil; güncel kullanım ihtiyaçlarına daha doğru cevap veren bir yapıya dönüştürmektir. Tekirdağ ve Süleymanpaşa’da konut, ofis ve ticari alan tadilatlarında ihtiyaç programını, yapı koşullarını ve bütçeyi birlikte değerlendiriyoruz.', 'Pioneer, tadilat işlerinde iç mimari kararları, teknik altyapıyı, malzeme seçimini ve uygulama sırasını tek plan altında toplar. Böylece mekânın karakteri güçlenirken, uygulama sırasında ortaya çıkabilecek sürprizler daha baştan kontrol altına alınır.', 'Nitelikli tadilat; doğru keşif, net imalat kapsamı ve kontrollü saha uygulamasıyla tamamlanır. Mekânınızı birlikte inceleyip yenileme rotasını belirleyebiliriz.', ['Keşif & ihtiyaç', 'Mekânın mevcut durumunu, kullanımını ve geliştirme ihtiyacını tespit ederiz.'], ['Tasarım & metraj', 'Malzeme, detay ve iş kalemlerini uygulanabilir bir plana dönüştürürüz.'], ['Uygulama & kontrol', 'Şantiye sürecini kalite, süre ve temiz teslim kriterleriyle yönetiriz.']],
        'ic-mimari': ['İç Mimari', 'İç Mimari; ölçü, ışık, malzeme ve mobilya kararlarının günlük yaşamla buluştuğu yerdir. Tekirdağ’da konut, villa, ofis ve dükkan iç mimari projelerinde mekânın karakterini kullanıcı alışkanlıkları ve uzun ömürlü kullanım hedefiyle tasarlarız.', 'Pioneer Mimarlık, iç mimariyi dekoratif bir katman olarak değil, yapının bütününü tamamlayan bir tasarım sistemi olarak ele alır. Plan kurgusundan aydınlatmaya, sabit mobilyadan yüzey seçimine kadar her kararın birbirini desteklemesini sağlar.', 'Mekânın potansiyelini, doğru ölçü ve kişiye özel detaylarla görünür kılmak için ilk görüşmede ihtiyaçlarınızı ve kullanım senaryonuzu konuşabiliriz.', ['Kullanım senaryosu', 'Yaşam veya çalışma biçimini plan kararlarının temel girdisi haline getiririz.'], ['Malzeme & ışık', 'Doku, renk, aydınlatma ve sabit elemanları bütüncül biçimde seçeriz.'], ['Uygulama detayı', 'Tasarımın sahada doğru karşılık bulması için uygulama sürecini takip ederiz.']],
        'ofis-dukkan': ['Ofis & Dükkan', 'Ofis ve dükkan projelerinde mekânın ilk izlenimi, operasyonel akış kadar önemlidir. Tekirdağ ve Süleymanpaşa’da ticari alanların planlamasını marka kimliği, kullanıcı sirkülasyonu, görünürlük ve uzun vadeli işletme ihtiyacıyla birlikte ele alıyoruz.', 'Pioneer, ofis ve dükkan tasarımında mimari proje ile iç mimari uygulamayı aynı dilde geliştirir. Doğru giriş, cephe, sergileme, çalışma ve servis alanı dengesi; ticari yapının hem günlük performansını hem de gayrimenkul değerini güçlendirir.', 'Yeni bir ticari alan, renovasyon veya karma kullanım projesi için mekânın hedefini ve uygulama kapsamını birlikte netleştirebiliriz.', ['İşletme analizi', 'Marka, kullanıcı, müşteri akışı ve alan ihtiyacını birlikte okuruz.'], ['Mekânsal kurgu', 'Plan, cephe, çalışma alanı ve servis akışını güçlü bir bütün halinde tasarlarız.'], ['Teslim koordinasyonu', 'Uygulamayı işletmenin açılış veya kullanım takvimiyle uyumlu ilerletiriz.']],
        'villa-insaati': ['Villa İnşaatı', 'Villa inşaatı, arsaya yerleşen kütleden iç mekândaki en küçük ayrıntıya kadar bütüncül karar gerektirir. Tekirdağ ve Süleymanpaşa’da villa projelerinde yönlenme, manzara, mahremiyet, bahçe ilişkisi ve günlük yaşam ihtiyaçlarını bir arada değerlendiriyoruz.', 'Pioneer İnşaat; mimari proje, ruhsat takibi, iç mimari kararlar ve şantiye yönetimini villa inşaatının aynı programında toplar. Bu sayede yapı, ilk tasarım niyetinden teslim anına kadar tutarlı ve uygulanabilir bir çizgide ilerler.', 'Arsanız için villa inşaatı düşünüyorsanız, ilk görüşmede yerleşim imkânını, yaşam senaryosunu ve uygulama hedefini birlikte değerlendirebiliriz.', ['Arsa yerleşimi', 'Işık, manzara, erişim ve mahremiyet kararlarını parsel koşullarıyla birlikte kurarız.'], ['Mimari & teknik proje', 'Yaşam biçimine uygun planı ruhsat ve uygulama gereklilikleriyle geliştiririz.'], ['Anahtar teslim yapım', 'Saha üretimini kalite, süre ve detay kontrolüyle yönetiriz.']],
        'cephe-yenileme': ['Cephe Yenileme', 'Cephe yenileme, yapının dış görünüşünü güncellemenin ötesinde; dayanım, enerji performansı ve kent içindeki kimliğini birlikte iyileştirme fırsatıdır. Tekirdağ ve Süleymanpaşa’da mevcut yapılara yeni bir ifade kazandırırken yapı kabuğunun teknik ihtiyaçlarını da dikkate alıyoruz.', 'Pioneer, cephe yenileme kararında mevcut yüzeyi, malzeme davranışını, ısı ve su etkilerini, bakım gereksinimini ve mimari karakteri birlikte inceler. Böylece seçilen çözüm yalnızca ilk gün etkileyici değil, zaman içinde sürdürülebilir olur.', 'Yapınızın cephesi için yenileme ihtiyacını ve olası uygulama alternatiflerini yerinde değerlendirmek üzere iletişime geçebilirsiniz.', ['Mevcut kabuk analizi', 'Yüzey, detay, hasar ve performans ihtiyacını saha koşullarıyla tespit ederiz.'], ['Tasarım alternatifi', 'Malzeme, renk, oran ve teknik katmanları yapının karakterine göre belirleriz.'], ['Uygulama kontrolü', 'Cephe imalatını detay, birleşim ve teslim kalitesi açısından takip ederiz.']],
        'izolasyon-isleri': ['İzolasyon İşleri', 'İzolasyon işleri, yapı konforu ve uzun ömürlülüğü için temel bir yatırımdır. Isı, su ve nem etkilerini doğru okumak; uygulama detaylarını yapının mevcut kabuğuna göre seçmek gerekir. Tekirdağ’ın iklim koşullarında doğru izolasyon, enerji verimliliği ve iç mekân konforunu birlikte destekler.', 'Pioneer, izolasyon işlerini cephe yenileme, tadilat veya yeni inşaat süreçlerinin doğal bir parçası olarak ele alır. Keşif, malzeme seçimi, detay çözümü ve saha kontrolü arasındaki ilişkiyi kurarak uygulamanın kalıcı sonuç vermesine odaklanır.', 'Yapınızın yalıtım ihtiyacını, mevcut durumunu ve uygulama seçeneklerini teknik bir ön değerlendirmeyle birlikte ele alabiliriz.', ['Yapı kabuğu incelemesi', 'Isı, su ve nem kaynaklı riskleri mevcut detaylar üzerinden değerlendiririz.'], ['Doğru sistem seçimi', 'Yapının ihtiyacına uygun malzeme ve katmanlaşmayı belirleriz.'], ['Detaylı uygulama', 'Birleşim noktaları ve saha kontrolüyle sistemin sürekliliğini koruruz.']],
        'depo-sanayi-yapilari': ['Depo & Sanayi Yapıları', 'Depo ve sanayi yapılarında tasarım, operasyonun ritmine hizmet etmelidir. Araç girişleri, yükleme, depolama, üretim, personel güvenliği ve büyüme senaryosu; projenin ilk kararlarından itibaren birlikte düşünülmelidir. Tekirdağ’da sanayi ve lojistik ihtiyaçları için uygulanabilir tesis çözümleri geliştiriyoruz.', 'Pioneer İnşaat, depo ve sanayi yapılarında arsa fizibilitesi, mimari proje, ruhsat takibi ve şantiye yönetimini tek programda ele alır. Böylece yatırımcı için üretim veya lojistik hedefiyle uyumlu, işleyen ve uzun ömürlü bir yapı sistemi oluşturulur.', 'Yeni tesis, depo veya mevcut sanayi yapısının geliştirilmesi için operasyonunuzu ve arsanızın koşullarını birlikte değerlendirebiliriz.', ['Operasyon analizi', 'Üretim, depolama, araç ve personel akışını ihtiyaç programına dönüştürürüz.'], ['Tesis kurgusu', 'Yapı ölçeğini, güvenlik ve büyüme hedefiyle uyumlu biçimde planlarız.'], ['Uygulama yönetimi', 'Saha programını teknik kalite, zaman ve yatırım hedefi doğrultusunda takip ederiz.']],
        'arsa-fizibilitesi': ['Arsa Fizibilitesi', 'Arsa fizibilitesi, yatırım kararından önce arsanın gerçek potansiyelini görünür hale getirir. İmar koşulları, yapılaşma kapasitesi, çevre verileri, kullanım türü, maliyet ve piyasa beklentisi birlikte değerlendirildiğinde doğru geliştirme senaryosu ortaya çıkar.', 'Tekirdağ ve Süleymanpaşa’da arsa fizibilitesi çalışırken yalnızca bugünün parsel verisine odaklanmayız. Konut, ofis, dükkan, villa, depo veya karma kullanım alternatiflerini teknik uygulanabilirlik ve gayrimenkul değeri açısından karşılaştırırız.', 'Bir arsa için teklif vermeden, yatırım ortaklığına girmeden veya proje üretmeden önce fizibilite yoluyla riskleri ve fırsatları birlikte okuyabiliriz.', ['Veri & imar okuması', 'Parsel, plan notu, çevre ve altyapı verilerini sistemli biçimde toplarız.'], ['Alternatif geliştirme', 'Farklı kullanım senaryolarını alan, maliyet ve değer açısından karşılaştırırız.'], ['Yatırım yol haritası', 'Seçilen senaryoyu proje, ruhsat ve uygulama sırasıyla somutlaştırırız.']],
        'gayrimenkul-danismanligi': ['Gayrimenkul Danışmanlığı', 'Gayrimenkul danışmanlığı; bir mülkün konumu, kullanım imkânı, geliştirme potansiyeli ve proje değeri hakkında doğru karar vermeyi gerektirir. Pioneer, mimarlık ve inşaat bilgisiyle gayrimenkulü sadece alım-satım değil, değer yaratma perspektifinden değerlendirir.', 'Tekirdağ ve Süleymanpaşa’daki arsa, mevcut yapı veya ticari gayrimenkul için fizibilite, tadilat, cephe yenileme, dönüşüm ya da yeni proje seçeneklerini birlikte ele alırız. Böylece karar, yalnızca güncel durum üzerinden değil, gelecekteki kullanım ve yatırım senaryoları üzerinden kurulur.', 'Mülkünüzün potansiyelini planlı bir değerlendirmeyle görmek için bize ulaşabilir; doğru proje veya geliştirme yaklaşımını birlikte belirleyebilirsiniz.', ['Mülk incelemesi', 'Konum, kullanım, teknik durum ve çevresel verileri birlikte değerlendiririz.'], ['Değer senaryosu', 'Geliştirme, yenileme veya yeniden kullanım alternatiflerini karşılaştırırız.'], ['Karar desteği', 'Mimari ve uygulama bilgisini yatırım hedefinizle aynı çerçevede buluştururuz.']],
        'proje-yonetimi': ['Proje Yönetimi', 'Proje yönetimi; tasarım, bütçe, iş programı, satın alma ve uygulama kararlarını aynı hedefe bağlayan disiplindir. Yapı ölçeği ne olursa olsun, doğru zamanlama ve açık sorumluluk dağılımı olmadan mimari kaliteyi sahada korumak güçleşir.', 'Pioneer İnşaat, Tekirdağ ve Süleymanpaşa’daki projelerde tasarım kararlarının uygulanabilirliğini sürekli gözetir. İş programını, ekip koordinasyonunu, maliyet kontrolünü ve kalite takibini görünür bir proje çerçevesinde bir araya getiririz.', 'Yeni inşaat, tadilat veya dönüşüm projenizde sürecin nerede olduğunu görmek ve sonraki adımları netleştirmek için proje yönetimi desteği talep edebilirsiniz.', ['Hedef & program', 'Kapsamı, süre hedefini, bütçe çerçevesini ve kritik karar noktalarını belirleriz.'], ['Ekip koordinasyonu', 'Tasarımcı, teknik ekip, tedarik ve saha arasında düzenli bilgi akışı kurarız.'], ['Takip & raporlama', 'İlerlemeyi kalite, maliyet ve zaman verileriyle değerlendiririz.']],
        'santiye-yonetimi': ['Şantiye Yönetimi', 'Şantiye yönetimi, projenin sahada doğru sırayla ve doğru detayla üretilmesini sağlar. İşçilik, malzeme, ekip güvenliği, imalat sırası ve kalite kontrolü her gün aynı dikkatle ele alınmalıdır. Bu disiplin, tasarımın gerçek yapıya dönüşmesini mümkün kılar.', 'Pioneer İnşaat, şantiye yönetiminde proje kararlarını uygulama programıyla birlikte takip eder. Tekirdağ ve Süleymanpaşa’da konut, villa, ofis, dükkan ve ticari yapı şantiyelerinde iletişimi, kontrol noktalarını ve teslim beklentisini açık biçimde yönetiriz.', 'Sahadaki iş programını güçlendirmek, uygulama kalitesini izlemek veya teslim sürecini sistemli hale getirmek için şantiye yönetimi desteğiyle ilerleyebilirsiniz.', ['İş programı', 'İmalatların sırasını, ekip ihtiyaçlarını ve kritik teslim tarihlerini planlarız.'], ['Saha denetimi', 'Detay, malzeme ve işçilik kalitesini proje hedeflerine göre kontrol ederiz.'], ['Teslim disiplini', 'Eksiklerin tamamlanması ve kullanım öncesi kontroller için net bir kapanış süreci kurarız.']]
    };
    const page = document.querySelector('[data-service-template]');
    const footerNavigation = document.querySelector('[data-service-footer-links]');
    const year = document.querySelector('[data-service-year]');
    if (footerNavigation) footerNavigation.innerHTML = services.map(([label, href]) => `<a href="${href}">${label}</a>`).join('');
    if (year) year.textContent = new Date().getFullYear();
    if (!page) return;
    const key = page.dataset.serviceTemplate;
    const data = content[key];
    if (!data) return;
    const [title, first, second, closing, stepOne, stepTwo, stepThree] = data;
    const image = page.dataset.serviceImage;
    page.innerHTML = `<section class="service-page-hero"><img src="${image}" alt="Tekirdağ ${title} hizmeti"><div class="site-shell service-page-hero__content"><p class="eyebrow"><span></span> Tekirdağ · Süleymanpaşa</p><h1>${title.split(' ').slice(0, -1).join(' ') || title}<br><em>${title.includes(' ') ? title.split(' ').slice(-1)[0] : 'Hizmeti'}.</em></h1><p>${first}</p></div></section><article class="site-shell service-story"><div><p class="eyebrow"><span></span> Pioneer İnşaat</p><h2>Doğru kararlarla<br><em>kalıcı sonuçlar.</em></h2></div><div class="service-story__copy"><p>${first}</p><p>${second}</p></div></article><section class="service-steps"><div class="site-shell"><div class="service-steps__heading"><p class="eyebrow"><span></span> Çalışma sistemimiz</p><h2>Üç aşamada<br><em>kontrollü ilerleme.</em></h2></div><div class="service-steps__grid"><article class="service-step"><span>01</span><h3>${stepOne[0]}</h3><p>${stepOne[1]}</p></article><article class="service-step"><span>02</span><h3>${stepTwo[0]}</h3><p>${stepTwo[1]}</p></article><article class="service-step"><span>03</span><h3>${stepThree[0]}</h3><p>${stepThree[1]}</p></article></div></div></section><section class="site-shell service-closing"><div class="service-closing__content"><p class="eyebrow"><span></span> Ön görüşme</p><h2>Projenizi birlikte<br><em>değerlendirelim.</em></h2><p>${closing}</p><a class="button button--gold" href="mailto:info@pioneermimarlik.com?subject=${encodeURIComponent(title + ' Görüşmesi')}">Ön görüşme talep et <span aria-hidden="true">↗</span></a></div></section>`;
});
